// @starchart generated — do not edit
// Facts as code, generated by STARCHART from .starchart/. Regenerate with `starchart codegen`.
/* eslint-disable */

// ── addon:pro ──

// @starchart anchors addon:pro.billing
export const ADDON_PRO_BILLING = "monthly";
// @starchart anchors addon:pro.features
export const ADDON_PRO_FEATURES = ["Themes", "iCloud sync"] as const;
// @starchart anchors addon:pro.name
export const ADDON_PRO_NAME = "Nebula Pro";
// @starchart anchors addon:pro.price.eur
export const ADDON_PRO_PRICE_EUR = 4.99;
// @starchart anchors addon:pro.price.usd
export const ADDON_PRO_PRICE_USD = 4.99;
// @starchart anchors addon:pro.productId
export const ADDON_PRO_PRODUCT_ID = "nebula_pro_monthly";
// @starchart anchors addon:pro.status
export const ADDON_PRO_STATUS = "active";

export const ADDON_PRO = {
  billing: ADDON_PRO_BILLING,
  features: ADDON_PRO_FEATURES,
  name: ADDON_PRO_NAME,
  price: {
    eur: ADDON_PRO_PRICE_EUR,
    usd: ADDON_PRO_PRICE_USD,
  },
  productId: ADDON_PRO_PRODUCT_ID,
  status: ADDON_PRO_STATUS,
} as const;

/** Every leaf fact by id. */
export const FACTS = {
  "addon:pro.billing": ADDON_PRO_BILLING,
  "addon:pro.features": ADDON_PRO_FEATURES,
  "addon:pro.name": ADDON_PRO_NAME,
  "addon:pro.price.eur": ADDON_PRO_PRICE_EUR,
  "addon:pro.price.usd": ADDON_PRO_PRICE_USD,
  "addon:pro.productId": ADDON_PRO_PRODUCT_ID,
  "addon:pro.status": ADDON_PRO_STATUS,
} as const;

export type FactId = keyof typeof FACTS;
