import type { Graph } from "../core/graph.js";
import {
  GENERATED_MARKER,
  arrayElementType,
  collectEntities,
  commentSafe,
  isPlainObject,
  pascalCase,
  sortedEntries,
  uniqueNamer,
  upperSnake,
  type FactTree,
} from "./tree.js";

const KOTLIN_HARD_KEYWORDS = new Set([
  "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface", "is", "null",
  "object", "package", "return", "super", "this", "throw", "true", "try", "typealias", "typeof", "val", "var", "when",
  "while",
]);
const KOTLIN_RESERVED_TYPES = new Set(["Any", "String", "Int", "Long", "Double", "Boolean", "List", "Unit", "Nothing", "Companion"]);

const objectName = (raw: string) => {
  const name = pascalCase(raw);
  return KOTLIN_RESERVED_TYPES.has(name) ? `${name}_` : name;
};

/** Kotlin string literal: escapes quotes, backslashes, `$` templates, control and non-ASCII characters. */
export function kotlinString(value: string): string {
  let out = '"';
  for (let i = 0; i < value.length; i++) {
    const ch = value[i]!;
    const code = value.charCodeAt(i);
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "$") out += "\\$";
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (ch === "\b") out += "\\b";
    else if (code < 0x20 || code > 0x7e) out += `\\u${code.toString(16).toUpperCase().padStart(4, "0")}`;
    else out += ch;
  }
  return `${out}"`;
}

function kotlinDouble(n: number): string {
  if (Number.isNaN(n)) return "Double.NaN";
  if (!Number.isFinite(n)) return n > 0 ? "Double.POSITIVE_INFINITY" : "Double.NEGATIVE_INFINITY";
  const s = String(n);
  return /[.eE]/.test(s) ? s : `${s}.0`;
}

const INT_MIN = -2147483648;
const INT_MAX = 2147483647;

function kotlinNumber(n: number): { literal: string; type: "Int" | "Long" | "Double" } {
  if (Number.isSafeInteger(n)) {
    if (n >= INT_MIN && n <= INT_MAX) return { literal: String(n), type: "Int" };
    return { literal: `${n}L`, type: "Long" };
  }
  return { literal: kotlinDouble(n), type: "Double" };
}

function listOf(values: readonly unknown[], kind: "string" | "int" | "double" | "bool"): { literal: string; type: string } {
  if (kind === "string") {
    return { literal: values.length ? `listOf(${values.map((v) => kotlinString(String(v))).join(", ")})` : "emptyList()", type: "List<String>" };
  }
  if (kind === "bool") return { literal: values.length ? `listOf(${values.map((v) => (v ? "true" : "false")).join(", ")})` : "emptyList()", type: "List<Boolean>" };
  if (kind === "double") return { literal: `listOf(${values.map((v) => kotlinDouble(Number(v))).join(", ")})`, type: "List<Double>" };
  const nums = values.map((v) => Number(v));
  const long = nums.some((n) => n < INT_MIN || n > INT_MAX);
  return {
    literal: `listOf(${nums.map((n) => (long ? `${n}L` : String(n))).join(", ")})`,
    type: long ? "List<Long>" : "List<Int>",
  };
}

/**
 * `package <pkg>` + `object <Name> { object AddonPro { const val NAME: String = "Pro+" ... } }`.
 * `const val` is used for strings and primitives; lists and nullable values are plain `val`.
 */
export function generateKotlin(graph: Graph, name = "StarchartFacts", pkg?: string, entities?: readonly string[]): string {
  const data = collectEntities(graph, entities);
  const out: string[] = [
    `// ${GENERATED_MARKER}`,
    "// Facts as code, generated by STARCHART from .starchart/. Regenerate with `starchart codegen`.",
    "",
  ];
  if (pkg) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(pkg)) throw new Error(`invalid Kotlin package name "${pkg}"`);
    const segments = pkg.split(".").map((s) => (KOTLIN_HARD_KEYWORDS.has(s) ? `\`${s}\`` : s));
    out.push(`package ${segments.join(".")}`, "");
  }
  const root = /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) && !KOTLIN_HARD_KEYWORDS.has(name) ? name : objectName(name);
  out.push(`object ${root} {`);
  const entityNames = uniqueNamer();
  data.forEach((e, index) => {
    if (index > 0) out.push("");
    out.push(`    /** ${commentSafe(e.id)} */`);
    out.push(`    object ${entityNames(objectName(e.id))} {`);
    emitChildren(out, e.children, "        ");
    out.push("    }");
  });
  out.push("}", "");
  return out.join("\n");
}

function emitChildren(out: string[], children: readonly FactTree[], indent: string): void {
  const members = uniqueNamer();
  const objects = uniqueNamer();
  for (const child of children) {
    if (child.kind === "group") {
      out.push(`${indent}object ${objects(objectName(child.key))} {`);
      emitChildren(out, child.children, `${indent}    `);
      out.push(`${indent}}`);
      continue;
    }
    out.push(`${indent}// @starchart anchors ${commentSafe(child.id)}`);
    emitValue(out, child.key, child.value, indent, members, objects);
  }
}

function emitValue(
  out: string[],
  key: string,
  value: unknown,
  indent: string,
  members: (n: string) => string,
  objects: (n: string) => string,
): void {
  if (isPlainObject(value)) {
    out.push(`${indent}object ${objects(objectName(key))} {`);
    const innerMembers = uniqueNamer();
    const innerObjects = uniqueNamer();
    for (const [k, v] of sortedEntries(value)) emitValue(out, k, v, `${indent}    `, innerMembers, innerObjects);
    out.push(`${indent}}`);
    return;
  }
  const name = members(upperSnake(key));
  if (value === null) {
    out.push(`${indent}val ${name}: String? = null`);
    return;
  }
  if (Array.isArray(value)) {
    const kind = arrayElementType(value);
    if (kind) {
      const { literal, type } = listOf(value, kind);
      out.push(`${indent}val ${name}: ${type} = ${literal}`);
    } else {
      out.push(`${indent}const val ${name}: String = ${kotlinString(JSON.stringify(value))} // JSON-encoded (not a homogeneous scalar list)`);
    }
    return;
  }
  switch (typeof value) {
    case "string":
      out.push(`${indent}const val ${name}: String = ${kotlinString(value)}`);
      return;
    case "boolean":
      out.push(`${indent}const val ${name}: Boolean = ${value ? "true" : "false"}`);
      return;
    case "number": {
      const { literal, type } = kotlinNumber(value);
      out.push(`${indent}const val ${name}: ${type} = ${literal}`);
      return;
    }
    default:
      out.push(`${indent}const val ${name}: String = ${kotlinString(String(value))}`);
  }
}
