import type { Graph } from "../core/graph.js";
import {
  GENERATED_MARKER,
  arrayElementType,
  camelCase,
  collectEntities,
  commentSafe,
  isPlainObject,
  pascalCase,
  sortedEntries,
  uniqueNamer,
  type FactTree,
} from "./tree.js";

const SWIFT_KEYWORDS = new Set([
  "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import", "init", "inout",
  "internal", "let", "open", "operator", "private", "precedencegroup", "protocol", "public", "rethrows", "static",
  "struct", "subscript", "typealias", "var", "break", "case", "catch", "continue", "default", "defer", "do", "else",
  "fallthrough", "for", "guard", "if", "in", "repeat", "return", "throw", "switch", "where", "while", "as", "false",
  "is", "nil", "self", "super", "throws", "true", "try", "await", "async", "any", "some", "_",
]);
/** Type names that would shadow standard meaning inside the generated namespace. */
const SWIFT_RESERVED_TYPES = new Set(["Type", "Self", "Protocol", "Any", "String", "Int", "Double", "Bool", "Array", "Optional"]);

const escapeKeyword = (name: string) => (SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name);
const typeName = (raw: string) => {
  const name = pascalCase(raw);
  return SWIFT_RESERVED_TYPES.has(name) ? `${name}_` : name;
};

/** Swift string literal with every special and non-ASCII character escaped. */
export function swiftString(value: string): string {
  let out = '"';
  for (const ch of value) {
    const cp = ch.codePointAt(0)!;
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (cp === 0) out += "\\0";
    else if (cp < 0x20 || cp > 0x7e) out += `\\u{${cp.toString(16).toUpperCase()}}`;
    else out += ch;
  }
  return `${out}"`;
}

function swiftDouble(n: number): string {
  if (Number.isNaN(n)) return "Double.nan";
  if (!Number.isFinite(n)) return n > 0 ? "Double.infinity" : "-Double.infinity";
  const s = String(n);
  return /[.eE]/.test(s) ? s : `${s}.0`;
}

function swiftScalar(value: string | number | boolean, kind: "string" | "int" | "double" | "bool"): string {
  switch (kind) {
    case "string":
      return swiftString(String(value));
    case "int":
      return String(value);
    case "double":
      return swiftDouble(Number(value));
    case "bool":
      return value ? "true" : "false";
  }
}

const SWIFT_TYPE = { string: "String", int: "Int", double: "Double", bool: "Bool" } as const;

/**
 * `public enum <Name> { public enum AddonPro { public static let name = "Pro+" ... } }`.
 * Nested fact groups (and object-valued facts) become nested enums.
 */
export function generateSwift(graph: Graph, name = "StarchartFacts", entities?: readonly string[]): string {
  const data = collectEntities(graph, entities);
  const out: string[] = [
    `// ${GENERATED_MARKER}`,
    "// Facts as code, generated by STARCHART from .starchart/. Regenerate with `starchart codegen`.",
    "",
    `public enum ${safeRootName(name)} {`,
  ];
  const entityNames = uniqueNamer();
  data.forEach((e, index) => {
    if (index > 0) out.push("");
    out.push(`    /// ${commentSafe(e.id)}`);
    out.push(`    public enum ${entityNames(typeName(e.id))} {`);
    emitChildren(out, e.children, "        ");
    out.push("    }");
  });
  out.push("}", "");
  return out.join("\n");
}

function safeRootName(name: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) && !SWIFT_KEYWORDS.has(name) ? name : typeName(name);
}

function emitChildren(out: string[], children: readonly FactTree[], indent: string): void {
  const members = uniqueNamer();
  const types = uniqueNamer();
  for (const child of children) {
    if (child.kind === "group") {
      out.push(`${indent}public enum ${types(typeName(child.key))} {`);
      emitChildren(out, child.children, `${indent}    `);
      out.push(`${indent}}`);
      continue;
    }
    out.push(`${indent}// @starchart anchors ${commentSafe(child.id)}`);
    emitValue(out, child.key, child.value, indent, members, types);
  }
}

function emitValue(
  out: string[],
  key: string,
  value: unknown,
  indent: string,
  members: (n: string) => string,
  types: (n: string) => string,
): void {
  if (isPlainObject(value)) {
    out.push(`${indent}public enum ${types(typeName(key))} {`);
    const innerMembers = uniqueNamer();
    const innerTypes = uniqueNamer();
    for (const [k, v] of sortedEntries(value)) emitValue(out, k, v, `${indent}    `, innerMembers, innerTypes);
    out.push(`${indent}}`);
    return;
  }
  const name = escapeKeyword(members(camelCase(key)));
  if (value === null) {
    out.push(`${indent}public static let ${name}: String? = nil`);
    return;
  }
  if (Array.isArray(value)) {
    const kind = arrayElementType(value);
    if (kind) {
      const items = value.map((v) => swiftScalar(v as string | number | boolean, kind)).join(", ");
      out.push(`${indent}public static let ${name}: [${SWIFT_TYPE[kind]}] = [${items}]`);
    } else {
      out.push(`${indent}public static let ${name}: String = ${swiftString(JSON.stringify(value))} // JSON-encoded (not a homogeneous scalar list)`);
    }
    return;
  }
  switch (typeof value) {
    case "string":
      out.push(`${indent}public static let ${name}: String = ${swiftString(value)}`);
      return;
    case "boolean":
      out.push(`${indent}public static let ${name}: Bool = ${value ? "true" : "false"}`);
      return;
    case "number":
      if (Number.isSafeInteger(value)) out.push(`${indent}public static let ${name}: Int = ${value}`);
      else out.push(`${indent}public static let ${name}: Double = ${swiftDouble(value)}`);
      return;
    default:
      out.push(`${indent}public static let ${name}: String = ${swiftString(String(value))}`);
  }
}
