import type { Graph } from "../core/graph.js";
import {
  GENERATED_MARKER,
  collectEntities,
  commentSafe,
  isPlainObject,
  leaves,
  sortedEntries,
  camelCase,
  uniqueNamer,
  upperSnake,
  type FactTree,
} from "./tree.js";

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** TypeScript literal for any JSON-like value. */
export function tsLiteral(value: unknown, indent = ""): string {
  if (value === null) return "null";
  switch (typeof value) {
    case "string":
      return JSON.stringify(value);
    case "number":
      if (Number.isNaN(value)) return "NaN";
      if (!Number.isFinite(value)) return value > 0 ? "Infinity" : "-Infinity";
      return String(value);
    case "boolean":
      return value ? "true" : "false";
    default:
      break;
  }
  const inner = `${indent}  `;
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const scalars = value.every((v) => v === null || typeof v !== "object");
    if (scalars) return `[${value.map((v) => tsLiteral(v)).join(", ")}]`;
    return `[\n${value.map((v) => `${inner}${tsLiteral(v, inner)},`).join("\n")}\n${indent}]`;
  }
  if (isPlainObject(value)) {
    const entries = sortedEntries(value);
    if (entries.length === 0) return "{}";
    return `{\n${entries.map(([k, v]) => `${inner}${tsKey(k)}: ${tsLiteral(v, inner)},`).join("\n")}\n${indent}}`;
  }
  return "undefined";
}

const tsKey = (key: string) => (IDENT.test(key) ? key : JSON.stringify(key));

/**
 * Emits one anchored top-level constant per leaf fact (so each generated symbol can be linked to
 * its fact), a nested `as const` object per entity composed from them, and a flat `FACTS` map.
 */
export function generateTypeScript(graph: Graph, entities?: readonly string[]): string {
  const data = collectEntities(graph, entities);
  const topLevel = uniqueNamer();
  topLevel("FACTS");
  const entityNames = new Map(data.map((e) => [e.id, topLevel(upperSnake(e.id))]));
  const leafNames = new Map<string, string>();
  for (const e of data) for (const leaf of leaves(e.children)) leafNames.set(leaf.id, topLevel(upperSnake(leaf.id)));

  const out: string[] = [
    `// ${GENERATED_MARKER}`,
    "// Facts as code, generated by STARCHART from .starchart/. Regenerate with `starchart codegen`.",
    "/* eslint-disable */",
    "",
  ];

  for (const e of data) {
    out.push(`// ── ${commentSafe(e.id)} ──`, "");
    for (const leaf of leaves(e.children)) {
      const needsConst = typeof leaf.value === "object" && leaf.value !== null;
      out.push(`// @starchart anchors ${commentSafe(leaf.id)}`);
      out.push(`export const ${leafNames.get(leaf.id)!} = ${tsLiteral(leaf.value)}${needsConst ? " as const" : ""};`);
    }
    out.push("");
    out.push(`export const ${entityNames.get(e.id)!} = ${objectOf(e.children, leafNames, "")} as const;`, "");
  }

  out.push("/** Every leaf fact by id. */");
  if (leafNames.size === 0) {
    out.push("export const FACTS = {} as const;");
  } else {
    out.push("export const FACTS = {");
    for (const e of data) for (const leaf of leaves(e.children)) out.push(`  ${JSON.stringify(leaf.id)}: ${leafNames.get(leaf.id)!},`);
    out.push("} as const;");
  }
  out.push("", "export type FactId = keyof typeof FACTS;", "");
  return out.join("\n");
}

function objectOf(children: readonly FactTree[], leafNames: Map<string, string>, indent: string): string {
  const inner = `${indent}  `;
  const names = uniqueNamer();
  const lines = children.map((child) => {
    const key = tsKey(names(camelCase(child.key)));
    const value = child.kind === "leaf" ? leafNames.get(child.id)! : objectOf(child.children, leafNames, inner);
    return `${inner}${key}: ${value},`;
  });
  return `{\n${lines.join("\n")}\n${indent}}`;
}
