// @starchart generated — do not edit
// Facts as code, generated by STARCHART from .starchart/. Regenerate with `starchart codegen`.

public enum StarchartFacts {
    /// addon:pro
    public enum AddonPro {
        // @starchart anchors addon:pro.billing
        public static let billing: String = "monthly"
        // @starchart anchors addon:pro.features
        public static let features: [String] = ["Themes", "iCloud sync"]
        // @starchart anchors addon:pro.name
        public static let name: String = "Nebula Pro"
        public enum Price {
            // @starchart anchors addon:pro.price.eur
            public static let eur: Double = 4.99
            // @starchart anchors addon:pro.price.usd
            public static let usd: Double = 4.99
        }
        // @starchart anchors addon:pro.productId
        public static let productId: String = "nebula_pro_monthly"
        // @starchart anchors addon:pro.status
        public static let status: String = "active"
    }
}
